version: "3.9"

services:
  mariadb:
    image: mariadb:11.3
    container_name: mariadb_bitacora
    restart: always
    env_file:
      - ./bitacoraBackend/.env
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"  
      MARIADB_DATABASE: ${NAME}
      MARIADB_USER: ${USER}
      MARIADB_PASSWORD: ${PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_bitacora
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: "" 
    ports:
      - "8080:80"
    depends_on:
      - mariadb

volumes:
  mariadb_data:
