# Generated by Django 5.2.7 on 2025-10-20 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='app_user',
        ),
    ]
