# Generated by Django 5.2.7 on 2025-10-27 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
